version: "3.8"
services:
  flask:
    build: "./flask/"
    volumes:
      - ./flask:/app
    # ports:
    #   - "8001:8000"
    environment:
      # - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    command: python app.py

  # Nginx Service
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/static:/home/www-data/
    # ports:
    #   - "8080:80"
    # Because of cloudflare is now portwording the port 8000
    # volumes:
    #   - ./www/:/var/www/html/

  # Cloudflare tunnel Service

  cloudflare:
    image: cloudflare/cloudflared:latest
    # command: tunnel --no-autoupdate run --token ${CF_TOKEN} --url http://linebot.nycu.site:80
    command: tunnel --no-autoupdate run --token ${CF_TOKEN}
    restart: always
    environment:
      - CF_TOKEN=${CF_TOKEN}
    